version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_network

  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - db_network

  sqlite:
    image: nouchka/sqlite3
    container_name: sqlite
    volumes:
      - sqlite_data:/data
    networks:
      - db_network

  oracle:
    image: gvenzl/oracle-xe
    container_name: oracle
    environment:
      ORACLE_PASSWORD: oracle_password
      APP_USER: user
      APP_USER_PASSWORD: user_password
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - db_network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - db_network

volumes:
  mysql_data:
  sqlite_data:
  oracle_data:
  postgres_data:
  mongo_data:

networks:
  db_network:
    driver: bridge
